# Generated by Django 2.1.5 on 2019-03-28 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0005_auto_20190328_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
