# Generated by Django 2.1.5 on 2019-03-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0006_toy_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='category',
            field=models.CharField(choices=[('T', 'Toy'), ('S', 'Souvenir')], default='Toys', max_length=1, null=True),
        ),
    ]
