# Generated by Django 2.1.5 on 2019-03-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0009_remove_toy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='category',
            field=models.CharField(choices=[('T', 'Toy'), ('S', 'Souvenir')], default='Toys', max_length=1, null=True),
        ),
    ]
