# Generated by Django 2.1.5 on 2019-07-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0010_toy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
        migrations.AddField(
            model_name='toy',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
        migrations.AddField(
            model_name='toy',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
        migrations.AddField(
            model_name='toy',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='static/image'),
        ),
    ]
