# Generated by Django 2.2.4 on 2019-08-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0014_toy_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name1', models.TextField(blank=True, default='', null=True)),
                ('phone_number1', models.TextField(blank=True, default='', null=True)),
                ('contact_name2', models.TextField(blank=True, default='', null=True)),
                ('phone_number2', models.TextField(blank=True, default='', null=True)),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('shop_name', models.TextField(blank=True, default='', null=True)),
                ('shop_type', models.TextField(blank=True, default='', null=True)),
                ('comments', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='toy',
            name='sale',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.CreateModel(
            name='OfflineOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('delivery_date', models.DateField(auto_now_add=True, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='wlwebsite.Customer')),
                ('toy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wlwebsite.Toy')),
            ],
        ),
    ]
