# Generated by Django 2.2.4 on 2019-08-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0015_auto_20190812_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='sale',
        ),
    ]
