# Generated by Django 2.2.4 on 2019-08-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0017_toy_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offlineorder',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='offlineorder',
            name='order_date',
        ),
        migrations.RemoveField(
            model_name='offlineorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='offlineorder',
            name='toy',
        ),
        migrations.AddField(
            model_name='offlineorder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='offlineorder',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offlineorder',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='OfflineOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=1, max_digits=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_items', to='wlwebsite.OfflineOrder')),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_order_items', to='wlwebsite.Toy')),
            ],
        ),
    ]
