# Generated by Django 2.2.4 on 2019-08-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0018_auto_20190812_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineorder',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
