# Generated by Django 2.1.5 on 2019-03-27 00:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_price', models.FloatField(blank=True, default=1000.0, null=True)),
                ('price', models.FloatField(blank=True, default=1000.0, null=True)),
                ('model', models.TextField(blank=True, default='', null=True)),
                ('manufactor', models.TextField(blank=True, default='', null=True)),
                ('stock', models.BooleanField(blank=True, default=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('weight', models.FloatField(blank=True, default=0.5, null=True)),
                ('sizes', models.TextField(blank=True, default='', null=True)),
                ('header', models.TextField(blank=True, default='', null=True)),
                ('product_code', models.TextField(blank=True, default='', null=True)),
                ('color', models.TextField(blank=True, default='', null=True)),
                ('madein', models.TextField(blank=True, default='Armenia', null=True)),
                ('quantity', models.IntegerField(blank=True, default=10, null=True)),
                ('adddate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('mainimage', models.ImageField(upload_to='woodenlego/static/woodenlego/image')),
                ('image1', models.ImageField(upload_to='woodenlego/static/woodenlego/image')),
                ('image2', models.ImageField(upload_to='woodenlego/static/woodenlego/image')),
                ('image3', models.ImageField(upload_to='woodenlego/static/woodenlego/image')),
                ('image4', models.ImageField(upload_to='woodenlego/static/woodenlego/image')),
            ],
            options={
                'ordering': ('-adddate',),
            },
        ),
        migrations.CreateModel(
            name='ToyReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default='', null=True)),
                ('reviewtext', models.TextField(blank=True, default='', null=True)),
                ('reviewrate', models.IntegerField(blank=True, default=5, null=True)),
                ('reviewdate', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wlwebsite.Toy')),
            ],
        ),
    ]
