# Generated by Django 2.1.5 on 2019-03-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wlwebsite', '0008_auto_20190330_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='category',
        ),
    ]
