# Generated by Django 2.1.5 on 2019-04-05 00:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homespot',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='homespot',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homespot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 1, 34, 29, 499927)),
        ),
        migrations.AlterField(
            model_name='homespot',
            name='picture',
            field=models.TextField(default=''),
        ),
    ]
