# Generated by Django 2.1.5 on 2019-04-05 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemap', '0002_auto_20190405_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='homespot',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='homespot',
            name='saledate',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='homespot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 1, 51, 56, 791999)),
        ),
    ]
