# Generated by Django 2.1.5 on 2019-04-05 00:56

import datetime
from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('housemap', '0003_auto_20190405_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homespot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 1, 56, 54, 739370)),
        ),
        migrations.AlterField(
            model_name='homespot',
            name='geom',
            field=djgeojson.fields.PointField(null=True),
        ),
    ]
