# Generated by Django 2.1.5 on 2019-04-05 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemap', '0004_auto_20190405_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homespot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 1, 57, 53, 797034)),
        ),
        migrations.AlterField(
            model_name='homespot',
            name='picture',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='homespot',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
