# Generated by Django 2.1.5 on 2019-04-05 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemap', '0005_auto_20190405_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homespot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 2, 33, 39, 91358)),
        ),
        migrations.AlterField(
            model_name='homespot',
            name='price',
            field=models.IntegerField(default=0.0, null=True),
        ),
    ]
