# Generated by Django 2.1.5 on 2019-04-05 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housemap', '0006_auto_20190405_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homespot',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 8, 8, 49, 731464)),
        ),
        migrations.AlterField(
            model_name='homespot',
            name='saledate',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 5, 8, 8, 49, 731464)),
        ),
    ]
